### ISSUE TITLE
Strange syntax highlighting for code blocks in org-mode

### ISSUE THREAD

**Issue by roife** [purcell/color-theme-sanityinc-tomorrow#114]
I'm using `color-theme-sanityinc-tomorrow-night` and get strange syntax highlighting in org-mode.
Here's screenshots.
- Normal syntax highlighting:
<img width="1504" alt="test 2018-08-02 at 17 14 38" src="https://user-images.githubusercontent.com/17700217/43575463-7c47decc-9679-11e8-977c-f15a9d894e0e.png">

- Strange syntax highlighting:
<img width="1504" alt="test 2018-08-02 at 17 14 49" src="https://user-images.githubusercontent.com/17700217/43575482-82453d42-9679-11e8-9c08-0baf7f15e5dd.png">

After changed to other themes, it worked well. If I turned off syntax highlighting, the code changed to orange instead of white.

**Comment by roife** [comment]
@drot
It suggested `org-block`.
<img width="1440" alt="test 2018-08-02 at 18 30 00" src="https://user-images.githubusercontent.com/17700217/43578677-16514d3e-9682-11e8-9cde-f169a69e9519.png">

**Comment by drot** [comment]
You can try editing `~/.emacs.d/elpa/color-theme-sanityinc-tomorrow-20180713.912/color-theme-sanityinc-tomorrow.el` and change the line:

`(org-block (:foreground ,orange))`

to something like:

`(org-block (:foreground ,foreground))`

restart Emacs and verify that the syntax highlight is correct.

**Comment by roife** [comment]
@drot
It works well now.

**Comment by drot** [comment]
I guess it boils down to color preference. By default `org-block` inherits from `shadow` so if we comment out that line from the theme file we get:

Before:
![screenshot-1533207627](https://user-images.githubusercontent.com/85483/43579983-29a812ce-9654-11e8-9cd9-0e4ad6cec660.png)

After:
![screenshot-1533207602](https://user-images.githubusercontent.com/85483/43579995-314e76da-9654-11e8-86ba-5356956df3a9.png)

Would this be a good compromise? If not you can always change the face color via Customize to make it permanent regardless of theme updates. Since I don't use Org mode extensively I don't know if the user needs some way to differentiate between Org code blocks and "true" code blocks. @purcell thoughts?

**Comment by roife** [comment]
It's a good solution.

**Comment by purcell** [comment]
> @purcell thoughts?

I don't have a strong opinion either way, so if you'd like to make that change, feel free. :-)
