### ISSUE TITLE
Potential option to keep font size consistent?

### ISSUE THREAD

**Issue by benreyn** [purcell/color-theme-sanityinc-tomorrow#147]
Just a suggestion, but I think it would be nice to have the option to have the font size stay consistent throughout emacs when using one of these themes. I have used `color-theme-sanityinc-tomorrow-eighties` for a long time now, and was always offput by the way that the title of my helm buffer was larger than the rest of the text in emacs. See below...

![_Minibuf-1_](https://user-images.githubusercontent.com/11561578/69340205-894f6e80-0c2c-11ea-9c04-da8b451f027a.png)

This is even more pronounced when I run a command like `helm-projectile-rg`...

![_scratch___—___236_x_63_](https://user-images.githubusercontent.com/11561578/69340285-bbf96700-0c2c-11ea-9dca-1e305bcd1d05.png)

Would you be open to adding a variable that the user of the theme can set that will ignore `:height` on all faces?

Im not sure of the feasibility of this, or if there is some reason that I don't know why those faces are so large comparatively, so I thought Id open this issue for discussion.

**Comment by purcell** [comment]
Yeah, I personally prefer the fixed consistent font sizes in almost all cases, particularly because I would like all the faces to be clearly distinct from each other even in a terminal window: for that reason, I also don't really like box outlines as a primary indicator of a face.

I don't use helm. I quite like org titles being larger than normal text, though, so I'm not keen on making this configurable via a global toggle var. How would it be for you if we only used larger sizes for faces that are headings in documentation or word-processing buffers?

/cc @manuel-uberti

**Comment by benreyn** [comment]
> How would it be for you if we only used larger sizes for faces that are headings in documentation or word-processing buffers?

That would be great 👍 Its really just the Helm stuff that distracts me during my workflow.

**Comment by manuel-uberti** [comment]
Interesting. When customising Helm faces for this theme, I tried to stick to what Helm already offers in terms of height, but I guess it would be enough to set the height for `helm-source-header` to `1.0` to fix this.

**Comment by manuel-uberti** [comment]
@purcell do you want me to provide a PR for this? Shouldn't take me long. :)

**Comment by benreyn** [comment]
Ive already got a branch on my fork that has this fix. In my version I just omitted the `:height` keywork on `helm-source-header` It ends up looking like this...

<img width="597" alt="_Minibuf-1_" src="https://user-images.githubusercontent.com/11561578/69434609-955a2f80-0d03-11ea-80f4-d6726f86e336.png">

I can PR that if its what we want, but I think I was wondering if we wanted to make it configurable.

**Comment by manuel-uberti** [comment]
It looks great to me, and on my fork I get the same by setting `:height` to `1.0`, so let's see what @purcell prefers.

re: configurability. I'd prefer not, because I like @purcell's suggestion of fixing larger sizes for faces that are headings in documentation or word-processing buffers. It'd keep the theme simpler, IMHO.

Totally up to him, of course. :)

**Comment by manuel-uberti** [comment]
Actually, since it works without setting the `:height`, I vote for your approach. :+1:

**Comment by benreyn** [comment]
I went ahead and PR-ed that change here...

https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/148

We can decide how to move forward from there once @purcell chimes in 😄

**Comment by purcell** [comment]
Merged that fix, thanks. Still open to having more `:height`s removed to match my suggestion above.

**Comment by manuel-uberti** [comment]
I'll work on it.
