### ISSUE TITLE
Colors in Ruby don't match the screenshots on the chriskempson repo

### ISSUE THREAD

**Issue by violetbaddley** [purcell/color-theme-sanityinc-tomorrow#42]
I am a huge fan of the Tomorrow Night theme, but it appears different in emacs than the same theme does in most other editors, such as vim, TextMate, and Sublime. The reference photo on chriskempson's Readme looks like

<img width="337" alt="tomorrow-night" src="https://raw.githubusercontent.com/ChrisKempson/Tomorrow-Theme/master/Images/Tomorrow-Night.png">

Whereas when I install and use this package in the Ruby major mode, it looks like

<img width="337" alt="screen shot 2016-10-13 at 12 44 01" src="https://cloud.githubusercontent.com/assets/2660568/19362160/c59f45e4-9142-11e6-95a2-877f0d9750ff.png">

The colors are very different, and it lends a very different feel to the code.

Is this issue specific to the theme, or to the Ruby grammar? Is there anything you can suggest I do to remedy the difference?

**Comment by purcell** [comment]
Firstly, it's impossible to match the colours between Emacs and Sublime etc. because the grammars are different. In fact, there are even inconsistencies inside Emacs between how ruby-mode uses the built-in faces and how lisp-mode does it.

So I've really made no effort to use the "right colours for the right elements" because I don't think that's a well-defined problem. Instead, I've tried to apply the standard Tomorrow colours in a nice varied way, with the constraint that I've typically reserved red to indicate errors. These are very personal trade-offs, admittedly.

**Comment by purcell** [comment]
P.S. There are other versions of the tomorrow themes in the base16 themes package, so you can try those out. The face definitions are less complete there, though, so YMMV.
