### ISSUE TITLE
Changing the fringe background?

### ISSUE THREAD

**Issue by drot** [purcell/color-theme-sanityinc-tomorrow#91]
Could we change the `fringe` background color to `highlight`? Having them invisible makes some modes that use fringe space ugly (like magit-log in the images) plus you have to double check if that's really the line beginning. The color is subtle enough in my opinion and `region` already has its distinct background color so there should be no conflicts.

Before:
![old](https://user-images.githubusercontent.com/85483/29726626-c0a7e668-89d0-11e7-9ecd-b966b9e2b948.png)

After:
![new](https://user-images.githubusercontent.com/85483/29726636-c8db8e98-89d0-11e7-89c0-940b0e366add.png)

**Comment by purcell** [comment]
Yeah, _maybe_. This is actually how the theme used to be, and I deliberately moved away from it in order to have a more minimal look. Also, although it's possible to change the `linum` background to match, it has this unfortunate display issue:

<img width="383" alt="screen shot 2017-08-26 at 13 25 09" src="https://user-images.githubusercontent.com/5636/29737477-155d6fde-8a62-11e7-80ba-89d50f0d9daf.PNG">

If you can figure out a solution to that issue, I'd probably be open to the change.

**Comment by drot** [comment]
Yeah other themes suffer from this as well. Dunno if it would be a issue for long since Linum and nLinum are being phased out in favor of Emacs 26 native line number display:

![native](https://user-images.githubusercontent.com/85483/29740144-d11a8e9a-8a4f-11e7-80d6-084f61eccb2b.png)

**Comment by drot** [comment]
Looks great, thanks!

**Comment by purcell** [comment]
Cool :-)
